version: '3'

services:
  server:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '3000:3000'

  database:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - database_data:/var/lib/postgresql/data

  # redis:
  #   image: redis
  #   expose:
  #     - "6379"
  #   command: redis-server 

volumes:
  database_data:
    driver: local